<?php
function copy_article_init() {
    
}

function copy_article_node_presave($node) {
    if ($node->type == "article") {
        // Reset status when node is updated:
        $node->status = 0;
    }
}

function copy_article_node_insert($node) {
    if($node->type == "article") {
        $new_node = new stdClass(); // Create a new node object
        $new_node = $node;
        unset($new_node->nid);
        unset($new_node->vid);
        $new_node->type = "article_copy"; // Content type
        /*$new_node->language = LANGUAGE_NONE;
        node_object_prepare($new_node);  //Set some default values
        
        $new_node->title = $node->title;
        $new_node->body[$new_node->language][0]['value'] = $node->body[$node->language][0]['value'];
        $new_node->body[$new_node->language][0]['summary'] = $node->body[$node->language][0]['summary'];
        $new_node->body[$new_node->language][0]['format'] = $node->body[$node->language][0]['format'];*/
        
        $new_node->status = 1;   // (1 or 0): published or unpublished
        /*$new_node->promote = $node->promote;  // (1 or 0): promoted to front page or not
        $new_node->sticky = $node->sticky;  // (1 or 0): sticky at top of lists or not
        $new_node->comment = $node->comment;  // 2 = comments open, 1 = comments closed, 0 = comments hidden
        // Add author of the node
        $new_node->uid = $node->uid;
        // Set created date
        $new_node->date = $node->date;
        $new_node->created = $node->created;
        
        $new_node->path = $node->path;*/
        // Save the node
        node_save($new_node);
    }
}